#!/usr/bin/python3

import curses
import cursesview.util as util
from cursesview.screen import Screen
__author__ = 'Kellan Childers'
"""THIS IS ONLY A PLACEHOLDER."""


def app(stdscr):
    # Ensures a clean visual space.
    stdscr.clear()
    curses.curs_set(False)

    # Sets the three main colors for the app screen.
    # First color: text. Second color: background.
    curses.init_pair(1, curses.COLOR_WHITE, curses.COLOR_BLUE)
    curses.init_pair(2, curses.COLOR_BLACK, curses.COLOR_WHITE)
    curses.init_pair(3, curses.COLOR_BLACK, curses.COLOR_BLACK)
    # Set the background of the app to white.
    stdscr.bkgd(' ', curses.color_pair(2))

    util.add_title(stdscr, "Agile Engine by Kellan Childers")

    stdscr.refresh()
    stdscr.getkey()
"""
    console_height, console_width = stdscr.getmaxyx()
    main_screen = Screen(console_height, console_width)
    main_screen.show_intro()
    main_screen.start_shopping_list()

    while True:
        main_screen.clear_screen()
        main_screen.do_command()"""

if __name__ == "__main__":
    # curses.wrapper ensures that program will always fully exit from curses mode if an error occurs.
    curses.wrapper(app)
