#!/usr/bin/python3

import curses
import cursesview.util as util
from controller.colorcontroller import create_colorschemes
from cursesview.initialize import initialize_window
__author__ = 'Kellan Childers'
"""Use this as boilerplate to start new curses projects quickly"""


def app(stdscr):
    """

    :param stdscr:
    :return:
    """

    # Start up screen and standardize visuals.
    create_colorschemes()
    initialize_window(stdscr)
    util.add_title(stdscr, "Agile Engine by Kellan Childers")

    stdscr.getkey()

"""This may come in handy later.
   console_height, console_width = stdscr.getmaxyx()
   """

if __name__ == "__main__":
    # curses.wrapper ensures that program will always fully exit from curses mode if an error occurs.
    curses.wrapper(app)
